- name: Install Java (required for Jenkins)
  ansible.builtin.package:
    name: openjdk-11-jdk
    state: present

- name: Download and add the Jenkins GPG key to the trusted keyring
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins.gpg
    mode: '0644'


- name: Add Jenkins repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: 'deb [signed-by=/usr/share/keyrings/jenkins.gpg] https://pkg.jenkins.io/debian-stable binary/'
    create: yes


- name: Install Jenkins
  ansible.builtin.apt:
    update_cache: yes
    name: jenkins
    state: latest
