pipeline {
    agent any
    environment {
        DOCKER_LOGIN=credentials('DOCKER_LOGIN')
    }
    stages{
        stage('Test') {
            steps {
                sh 'echo "Running tests..."'
            }
        }
        stage('Build') {
            steps {
                sh 'docker stop jenkinsapp'
                sh 'docker rm jenkinsapp'
                sh 'docker build -t justinbood/jenkinsapp .'
                sh 'docker login -u ${DOCKER_LOGIN_USR} -p ${DOCKER_LOGIN_PSW}'
                sh 'docker push justinbood/jenkinsapp'
                sh 'docker run -d -p 5000:5000 --name jenkinsapp justinbood/jenkinsapp'
                
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploying'
                
            }
        }
    }
}