pipeline {
    agent any
    environment {
        DOCKER_LOGIN=credentials('DOCKER_LOGIN')
    }
    stages{
        stage('Test') {
            steps {
                sh 'echo "Running tests..."'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t jusinbood/jenkinsapp .'
                sh 'docker login -u ${DOCKER_LOGIN_USR} -p ${DOCKER_LOGIN_PSW}'
                sh 'docker push jusinbood/jenkinsapp'
                
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5000:5000 --name app1 jusinbood/jenkinsapp'
                
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'Job succeeded!'
        }
        failure {
            echo 'Job failed!'
        }
    }
}